# Folder paths
PROCS: gtkwave_lab

# Assembler config 
FILT_ASM: True
ACTIVE_FILE: main  
ASM_COMP: ALWAYS
MODE: LAB9

# Logging
LOG_LEVEL: INFO     
LOG_LOC: TERM       
LOG_DIR: log
LOG_ROLL: True 

# Processor config
EN_VERILOG_CHECK: False

# HTML config
THEME: DARK
AUTO_OPEN: True

# Advanced
EN_CSV: False
OUT_ROLL: True
EN_MT: False