# Folder paths
PROCS: main

# Assembler config 
FILT_ASM: True
ACTIVE_FILE: baby   # Premade options are baby, hazardous, and final
ASM_COMP: AUTO      # Possible options are ALWAYS, NEVER, and AUTO
MODE: MIPS          # Possible modes are MIPS or LAB9

# Logging
LOG_LEVEL: INFO     # Possible level options are INFO, IVERILOG, WARN, ERROR, and NONE
LOG_LOC: TERM       # Possible location options are TERM and FILE
LOG_DIR: log
LOG_ROLL: True 

# Processor config
EN_VERILOG_CHECK: True

# HTML config
THEME: DARK
AUTO_OPEN: True

# Advanced
EN_CSV: False
OUT_ROLL: True
EN_MT: True